### ISSUE TITLE
Unexpected sequence

### ISSUE THREAD

**Issue by jerrylipeng** [mariodu/mongoose-id-autoinc#1]
The example.js generates a sequence of 109, 119, 129.. which I expect to be 100, 110, 120..
I suppose the code (from line 63) could be changed to:
          }, {
            'new':  true,
            upsert: true
          }, function (err, res) {

```
        if (!err)
          doc[options.field] = res.seq - options.step;
```

or
          }, {
            upsert: true
          }, function (err, res) {

```
        if (!err)
          doc[options.field] = res.seq;
```

**Comment by mariodu** [comment]
thanks for your issue, I will fix it tomorrow.

**Comment by mariodu** [comment]
The bug has already fixed!
