### ISSUE TITLE
提两个小问题和一个建议

### ISSUE THREAD

**Issue by JoneWang** [mariodu/mongoose-id-autoinc#2]
不错东西，发现两个无关痛痒的小问题
1. lib/mongooes-id-autoinc.js 名称中的mongooes应为mongoose
2. README中“4.可选字段”下面代码中"field"前面的逗号和后面的冒号是中文逗号和冒号

并且建议默认情况下默认保留_id原有的数据，使用id自增，因为_id中也是可以提取出一些，比如数据的时间戳等

**Comment by mariodu** [comment]
感谢你提出的问题和建议，不好意思，才看到。_id那个当时是为了自己好用才这样子的，想了一下，还是不要覆盖默认的比较好。已经更新好了。

**Comment by JoneWang** [comment]
thx :P
